@{
    NonNodeData = @{
        Exchange = @{
            AcceptedDomain        = @(
                @{
                    DomainType      = 'Authoritative'
                    Ensure          = 'Present'
                    MatchSubDomains = $false
                    OutboundOnly    = $false
                    Identity        = '{{TenantId}}'
                }
            )
            AntiPhishPolicy       = @(
                @{
                    Identity                            = 'Office365 AntiPhish Default'
                    AdminDisplayName                    = 'aa'
                    AuthenticationFailAction            = 'MoveToJmf'
                    Enabled                             = $true
                    EnableFirstContactSafetyTips        = $true
                    EnableMailboxIntelligence           = $true
                    EnableMailboxIntelligenceProtection = $true
                    EnableOrganizationDomainsProtection = $true
                    EnableSimilarDomainsSafetyTips      = $true
                    EnableSimilarUsersSafetyTips        = $true
                    EnableSpoofIntelligence             = $true
                    EnableTargetedDomainsProtection     = $false
                    EnableTargetedUserProtection        = $false
                    EnableUnauthenticatedSender         = $true
                    EnableUnusualCharactersSafetyTips   = $true
                    EnableViaTag                        = $true
                    Ensure                              = 'Present'
                    ImpersonationProtectionState        = 'Manual'
                    MailboxIntelligenceProtectionAction = 'MoveToJmf'
                    MailboxIntelligenceQuarantineTag    = 'DefaultFullAccessPolicy'
                    MakeDefault                         = $true
                    PhishThresholdLevel                 = '2'
                    SpoofQuarantineTag                  = 'DefaultFullAccessPolicy'
                    TargetedDomainQuarantineTag         = 'DefaultFullAccessPolicy'
                    TargetedUserProtectionAction        = 'Quarantine'
                    TargetedUserQuarantineTag           = 'DefaultFullAccessPolicy'
                }
            )
            AtpPolicyForO365      = @{
                AllowSafeDocsOpen       = $false
                EnableATPForSPOTeamsODB = $true
                EnableSafeDocs          = $true
                Ensure                  = 'Present'
            }
            AuthenticationPolicy  = @(
                @{
                    Identity                           = 'BlockBasic637775045994108741'
                    AllowBasicAuthActiveSync           = $false
                    AllowBasicAuthAutodiscover         = $false
                    AllowBasicAuthImap                 = $true
                    AllowBasicAuthMapi                 = $false
                    AllowBasicAuthOfflineAddressBook   = $false
                    AllowBasicAuthOutlookService       = $true
                    AllowBasicAuthPop                  = $true
                    AllowBasicAuthPowerShell           = $true
                    AllowBasicAuthReportingWebServices = $true
                    AllowBasicAuthRpc                  = $false
                    AllowBasicAuthSmtp                 = $true
                    AllowBasicAuthWebServices          = $false
                    Ensure                             = 'Present'
                }
            )
            OrganizationConfig    = @{
                ActivityBasedAuthenticationTimeoutEnabled                 = $true
                ActivityBasedAuthenticationTimeoutInterval                = '06:00:00'
                ActivityBasedAuthenticationTimeoutWithSingleSignOnEnabled = $true
                AppsForOfficeEnabled                                      = $true
                AsyncSendEnabled                                          = $true
                AuditDisabled                                             = $false
                AutodiscoverPartialDirSync                                = $false
                AutoExpandingArchive                                      = $false
                BlockMoveMessagesForGroupFolders                          = $false
                BookingsAddressEntryRestricted                            = $false
                BookingsAuthEnabled                                       = $false
                BookingsBlockedWordsEnabled                               = $false
                BookingsCreationOfCustomQuestionsRestricted               = $false
                BookingsEnabled                                           = $false
                BookingsExposureOfStaffDetailsRestricted                  = $false
                BookingsMembershipApprovalRequired                        = $false
                BookingsNamingPolicyEnabled                               = $false
                BookingsNamingPolicyPrefix                                = ''
                BookingsNamingPolicyPrefixEnabled                         = $false
                BookingsNamingPolicySuffix                                = ''
                BookingsNamingPolicySuffixEnabled                         = $false
                BookingsNotesEntryRestricted                              = $false
                BookingsPaymentsEnabled                                   = $false
                BookingsPhoneNumberEntryRestricted                        = $false
                BookingsSearchEngineIndexDisabled                         = $false
                BookingsSmsMicrosoftEnabled                               = $true
                BookingsSocialSharingRestricted                           = $false
                ByteEncoderTypeFor7BitCharsets                            = 0
                ComplianceMLBgdCrawlEnabled                               = $false
                ConnectorsActionableMessagesEnabled                       = $true
                ConnectorsEnabled                                         = $true
                ConnectorsEnabledForOutlook                               = $true
                ConnectorsEnabledForSharepoint                            = $true
                ConnectorsEnabledForTeams                                 = $true
                ConnectorsEnabledForYammer                                = $true
                CustomerLockboxEnabled                                    = $true
                DefaultAuthenticationPolicy                               = 'BlockBasic637775045994108741'
                DefaultGroupAccessType                                    = 'Private'
                DefaultMinutesToReduceLongEventsBy                        = 10
                DefaultMinutesToReduceShortEventsBy                       = 5
                DefaultPublicFolderDeletedItemRetention                   = '30.00:00:00'
                DefaultPublicFolderIssueWarningQuota                      = '1.7 GB (1,825,361,920 bytes)'
                DefaultPublicFolderMaxItemSize                            = 'Unlimited'
                DefaultPublicFolderMovedItemRetention                     = '7.00:00:00'
                DefaultPublicFolderProhibitPostQuota                      = '2 GB (2,147,483,648 bytes)'
                DirectReportsGroupAutoCreationEnabled                     = $false
                DisablePlusAddressInRecipients                            = $false
                ElcProcessingDisabled                                     = $false
                EnableOutlookEvents                                       = $false
                EndUserDLUpgradeFlowsDisabled                             = $false
                ExchangeNotificationEnabled                               = $true
                FindTimeAttendeeAuthenticationEnabled                     = $false
                FindTimeAutoScheduleDisabled                              = $false
                FindTimeLockPollForAttendeesEnabled                       = $false
                FindTimeOnlineMeetingOptionDisabled                       = $false
                IsGroupFoldersAndRulesEnabled                             = $false
                IsGroupMemberAllowedToEditContent                         = $false
                LeanPopoutEnabled                                         = $false
                LinkPreviewEnabled                                        = $true
                MailTipsAllTipsEnabled                                    = $true
                MailTipsExternalRecipientsTipsEnabled                     = $true
                MailTipsGroupMetricsEnabled                               = $true
                MailTipsLargeAudienceThreshold                            = 25
                MailTipsMailboxSourcedTipsEnabled                         = $true
                MaskClientIpInReceivedHeadersEnabled                      = $true
                MatchSenderOrganizerProperties                            = $false
                MessageHighlightsEnabled                                  = $true
                MessageRemindersEnabled                                   = $true
                MobileAppEducationEnabled                                 = $false
                OAuth2ClientProfileEnabled                                = $true
                OutlookGifPickerDisabled                                  = $false
                OutlookMobileGCCRestrictionsEnabled                       = $false
                OutlookPayEnabled                                         = $true
                OutlookTextPredictionDisabled                             = $false
                PublicComputersDetectionEnabled                           = $false
                PublicFoldersEnabled                                      = 'Local'
                PublicFolderShowClientControl                             = $false
                ReadTrackingEnabled                                       = $false
                SendFromAliasEnabled                                      = $false
                SharedDomainEmailAddressFlowEnabled                       = $true
                ShortenEventScopeDefault                                  = 'None'
                SmtpActionableMessagesEnabled                             = $true
                VisibleMeetingUpdateProperties                            = 'Location,AllProperties:15'
                WebPushNotificationsDisabled                              = $false
                WebSuggestedRepliesDisabled                               = $false
                WorkspaceTenantEnabled                                    = $true
            }
            OwaMailboxPolicy      = @(
                @{
                    Name                                                 = 'OwaMailboxPolicy-Default'
                    ActionForUnknownFileAndMIMETypes                     = 'Allow'
                    ActiveSyncIntegrationEnabled                         = $true
                    AdditionalStorageProvidersAvailable                  = $false
                    AllAddressListsEnabled                               = $true
                    AllowCopyContactsToDeviceAddressBook                 = $true
                    AllowedFileTypes                                     = @('.rpmsg', '.xlsx', '.xlsm', '.xlsb', '.vstx', '.vstm', '.vssx', '.vssm', '.vsdx', '.vsdm', '.tiff', '.pptx', '.pptm', '.ppsx', '.ppsm', '.docx', '.docm', '.zip', '.xls', '.wmv', '.wma', '.wav', '.vtx', '.vsx', '.vst', '.vss', '.vsd', '.vdx', '.txt', '.tif', '.rtf', '.pub', '.ppt', '.png', '.pdf', '.one', '.mp3', '.jpg', '.gif', '.doc', '.csv', '.bmp', '.avi')
                    AllowedMimeTypes                                     = @('image/jpeg', 'image/png', 'image/gif', 'image/bmp')
                    BlockedFileTypes                                     = @('.settingcontent-ms', '.printerexport', '.appcontent-ms', '.application', '.appref-ms', '.vsmacros', '.website', '.msh2xml', '.msh1xml', '.diagcab', '.webpnp', '.ps2xml', '.ps1xml', '.mshxml', '.gadget', '.theme', '.psdm1', '.mhtml', '.cdxml', '.xbap', '.vhdx', '.pyzw', '.pssc', '.psd1', '.psc2', '.psc1', '.msh2', '.msh1', '.jnlp', '.aspx', '.appx', '.xnk', '.xll', '.wsh', '.wsf', '.wsc', '.wsb', '.vsw', '.vhd', '.vbs', '.vbp', '.vbe', '.url', '.udl', '.tmp', '.shs', '.shb', '.sct', '.scr', '.scf', '.reg', '.pyz', '.pyw', '.pyo', '.pyc', '.pst', '.ps2', '.ps1', '.prg', '.prf', '.plg', '.pif', '.pcd', '.osd', '.ops', '.msu', '.mst', '.msp', '.msi', '.msh', '.msc', '.mht', '.mdz', '.mdw', '.mdt', '.mde', '.mdb', '.mda', '.mcf', '.maw', '.mav', '.mau', '.mat', '.mas', '.mar', '.maq', '.mam', '.mag', '.maf', '.mad', '.lnk', '.ksh', '.jse', '.jar', '.its', '.isp', '.iso', '.ins', '.inf', '.img', '.htc', '.hta', '.hpj', '.hlp', '.grp', '.fxp', '.exe', '.der', '.csh', '.crt', '.cpl', '.com', '.cnt', '.cmd', '.chm', '.cer', '.cab', '.bgi', '.bat', '.bas', '.asx', '.asp', '.app', '.apk', '.adp', '.ade', '.ws', '.vb', '.py', '.pl', '.js')
                    BlockedMimeTypes                                     = @('application/x-javascript', 'application/javascript', 'application/msaccess', 'x-internet-signup', 'text/javascript', 'application/prg', 'application/hta', 'text/scriplet')
                    BookingsMailboxCreationEnabled                       = $true
                    ClassicAttachmentsEnabled                            = $true
                    ConditionalAccessPolicy                              = 'Off'
                    DefaultTheme                                         = ''
                    DirectFileAccessOnPrivateComputersEnabled            = $false
                    DirectFileAccessOnPublicComputersEnabled             = $true
                    DisplayPhotosEnabled                                 = $true
                    Ensure                                               = 'Present'
                    ExplicitLogonEnabled                                 = $true
                    ExternalImageProxyEnabled                            = $true
                    FeedbackEnabled                                      = $true
                    ForceSaveAttachmentFilteringEnabled                  = $false
                    ForceSaveFileTypes                                   = @('.svgz', '.html', '.xml', '.swf', '.svg', '.spl', '.htm', '.dir', '.dcr')
                    ForceSaveMimeTypes                                   = @('Application/x-shockwave-flash', 'Application/octet-stream', 'Application/futuresplash', 'Application/x-director', 'application/xml', 'image/svg+xml', 'text/html', 'text/xml')
                    ForceWacViewingFirstOnPrivateComputers               = $false
                    ForceWacViewingFirstOnPublicComputers                = $false
                    FreCardsEnabled                                      = $true
                    GlobalAddressListEnabled                             = $true
                    GroupCreationEnabled                                 = $true
                    InstantMessagingEnabled                              = $true
                    InstantMessagingType                                 = 'Ocs'
                    InterestingCalendarsEnabled                          = $true
                    IRMEnabled                                           = $true
                    IsDefault                                            = $true
                    JournalEnabled                                       = $true
                    LocalEventsEnabled                                   = $false
                    LogonAndErrorLanguage                                = 0
                    MessagePreviewsDisabled                              = $false
                    NotesEnabled                                         = $true
                    NpsSurveysEnabled                                    = $true
                    OnSendAddinsEnabled                                  = $false
                    OrganizationEnabled                                  = $true
                    OutboundCharset                                      = 'AutoDetect'
                    OutlookBetaToggleEnabled                             = $true
                    OWALightEnabled                                      = $true
                    PersonalAccountCalendarsEnabled                      = $true
                    PhoneticSupportEnabled                               = $false
                    PlacesEnabled                                        = $true
                    PremiumClientEnabled                                 = $true
                    PrintWithoutDownloadEnabled                          = $true
                    ProjectMocaEnabled                                   = $false
                    PublicFoldersEnabled                                 = $true
                    RecoverDeletedItemsEnabled                           = $true
                    ReferenceAttachmentsEnabled                          = $true
                    RemindersAndNotificationsEnabled                     = $true
                    ReportJunkEmailEnabled                               = $true
                    RulesEnabled                                         = $true
                    SatisfactionEnabled                                  = $true
                    SaveAttachmentsToCloudEnabled                        = $true
                    SearchFoldersEnabled                                 = $true
                    SetPhotoEnabled                                      = $true
                    SetPhotoURL                                          = ''
                    ShowOnlineArchiveEnabled                             = $true
                    SignaturesEnabled                                    = $true
                    SkipCreateUnifiedGroupCustomSharepointClassification = $true
                    TeamSnapCalendarsEnabled                             = $true
                    TextMessagingEnabled                                 = $true
                    ThemeSelectionEnabled                                = $true
                    UMIntegrationEnabled                                 = $true
                    UseGB18030                                           = $false
                    UseISO885915                                         = $false
                    UserVoiceEnabled                                     = $true
                    WacEditingEnabled                                    = $true
                    WacExternalServicesEnabled                           = $true
                    WacOMEXEnabled                                       = $false
                    WacViewingOnPrivateComputersEnabled                  = $true
                    WacViewingOnPublicComputersEnabled                   = $true
                    WeatherEnabled                                       = $true
                    WebPartsFrameOptionsType                             = 'SameOrigin'
                }
            )
            ResourceConfiguration = @{
                Ensure                 = 'Present'
                ResourcePropertySchema = ''
            }
            TransportConfig       = @{
                AddressBookPolicyRoutingEnabled         = $false
                AllowLegacyTLSClients                   = $false
                ClearCategories                         = $true
                ConvertDisclaimerWrapperToEml           = $false
                DSNConversionMode                       = 'PreserveDSNBody'
                ExternalDelayDsnEnabled                 = $true
                ExternalDsnLanguageDetectionEnabled     = $true
                ExternalDsnSendHtml                     = $true
                HeaderPromotionModeSetting              = 'NoCreate'
                InternalDelayDsnEnabled                 = $true
                InternalDsnLanguageDetectionEnabled     = $true
                InternalDsnSendHtml                     = $true
                JournalingReportNdrTo                   = '<>'
                JournalMessageExpirationDays            = 0
                MaxRecipientEnvelopeLimit               = 'Unlimited'
                ReplyAllStormBlockDurationHours         = 6
                ReplyAllStormDetectionMinimumRecipients = 2500
                ReplyAllStormDetectionMinimumReplies    = 10
                ReplyAllStormProtectionEnabled          = $true
                Rfc2231EncodingEnabled                  = $false
                SmtpClientAuthenticationDisabled        = $true
            }
        }
    }
}
